server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/prompts/ {
        proxy_pass http://prompt-service:8000/prompts/;
        proxy_read_timeout 130s;
    }

    location /api/chats {
        rewrite ^/api/chats(.*)$ /chats$1 break;
        proxy_pass http://prompt-service:8000;
        proxy_read_timeout 130s;
    }

    location /api/reviews/ {
        proxy_pass http://review-service:8001/reviews/;
        proxy_read_timeout 40s;
    }

    location /api/document-chats {
        rewrite ^/api/document-chats(.*)$ /document-chats$1 break;
        proxy_pass http://prompt-service:8000;
        proxy_read_timeout 130s;
    }

    location /api/documents {
        rewrite ^/api/documents(.*)$ /documents$1 break;
        proxy_pass http://file-service:8003;
        client_max_body_size 15m;
        proxy_read_timeout 40s;
    }
}